# Generated by Django 6.1.1 on 2026-09-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price (₹)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('whatsapp_number', models.CharField(default='919876543210', max_length=15, verbose_name='WhatsApp Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
